### ISSUE TITLE
#1 User Story Set Up & Homepage

### ISSUE THREAD

**Issue by dorosiemers** [dorosiemers/capstone-test#1]
# Value Proposition
As a User, I want to land on the homepage and get a clear view of the different contents of the app.

# Description
The Apps Homepage should give an overview over the apps content.

![User Stories Skribble 1](https://user-images.githubusercontent.com/112318280/197201508-5ac235af-91c9-43b5-9323-d393147c8153.png)

# Acceptance Criteria
- [x] when I access the app land to a page with multiple containers
- [x] one main container holds 4 container in a column style
- [x] the 4 containers will each hold text

# Tasks
 - [x] create new react project
 - [x] remove unnecessary data
 - [x] add Home function in index.js
 - [x] add div to function
 - [x] add h1 to index.js
 - [x] add 3 h2s to index.js
 - [x] add p s to each h2

**Comment by edanum** [comment]
Die Akzeptanzkritierien sind als Aufgabe formuliert. Hier solltest du eher formulieren, was der branch erbringen muss, um die US zu erfüffeln. Zum Beispiel:
- when I access the app land to a page with multiple containers and a logo
- one main container holds the logo and 4 container in a column style
- the 4 container each hold text ....
 usw.

Die Story sollte ganz oben stehen unter value proposition. Der Screenshot danach unter der Überschrift description

**Comment by mpagels** [comment]
Looks very good to me Doro.

~~Maybe you could use this as second story to connect to one of the content pages. In the first story you could create a content page with the information. But it is up to you.~~

Very good work here. Keep up! ;-) ❤️

**Comment by dorosiemers** [comment]
> I'm not sure I understand exactly what you mean, Martin. Would you like to see me start with let's say the content page with static content? Because there's only going to be static content on the homepage. I decided to do a separate input page after our talk the other day. 😇
