### ISSUE TITLE
#2 User Story Content Pages

### ISSUE THREAD

**Issue by dorosiemers** [dorosiemers/capstone-test#2]
# Value Proposition
As a User, I want to visit the multiple different page of the application.

# Description
The different pages are created rudimentary.

![User Stories Skribble 2](https://user-images.githubusercontent.com/112318280/197210322-8b43587a-d3f0-421d-8b7d-04edde87aa22.png)

# Acceptance Criteria
- [ ] I can access three different additional pages 
- [ ] the form page holds a simple form with 4 inputs
- [ ] the list pages holds a simple list elements

# Tasks
 - [ ] create 3 different pages 
 - [ ] add a form with 4 inputs to the form page
 - [ ] add a list element to each list page
 - [ ] add basic styling/styled components

**Comment by edanum** [comment]
Nur als Vorschlag: du könntest dir das mehrfache einfügen der Headerkomponente ersparen, wenn du dir eine Layout-Komponente ertstellst. Auch die eigentliche Inhaltsseite müsstest du dann nur einmal global stylen

![image](https://user-images.githubusercontent.com/79711003/197216430-a1f60d8b-d5c4-4527-972e-3ae82bfb3fed.png)

ein Beispiel hierfür findest du in Ernsts Repo (https://github.com/Kheirah/nf-neue-fische-shop/blob/main/components/Layout.js)
