### ISSUE TITLE
#3 User Story Layout.js, Header and Navbar, Logo, Footer

### ISSUE THREAD

**Issue by dorosiemers** [dorosiemers/capstone-test#3]
# Value Proposition
As a User, I want to navigate easily between the different pages.

# Description
A Navbar is created in the Header with which the user can switch between pages. The Header is moved to a newly created Layout.js, to enable global styling later on. A Footer is also included in the Layout.js.

![User Stories Skribble 3](https://user-images.githubusercontent.com/112318280/197227724-5d65de5b-7df1-43a9-abb8-34107e151a2b.png)

# Acceptance Criteria
- [ ] the Layout.js contains both the Header and Footer element
- [ ] - [ ] I can access all pages via Navbar in the Header
- [ ] the Footer is in place 

# Tasks
 - [ ] create Layout.js 
 - [ ] create the Header and link it to Layout.js
 - [ ] create a Footer component and link it in the Layout.js
 - [ ] create a Navbar component and link the different pages
 - [ ] link the Navbar to the Header
