### ISSUE TITLE
#4 User Story Buttons 

### ISSUE THREAD

**Issue by dorosiemers** [dorosiemers/capstone-test#4]
# Value Proposition
As a User I want to use buttons to navigate from the homepage to the different detail pages.

# Description
To each overview section on the homepage a button is added that redirects the User to the respective details page. 

![User Stories Skribble 4](https://user-images.githubusercontent.com/112318280/197548898-01c7710e-7a94-4fc9-b16d-3d25a78eefbd.png)

# Acceptance Criteria
- [ ] I can access all pages via the buttons in the section on the homepage

# Tasks
 - [ ] create a button for each section on the homepage
 - [ ] route them to the respective details page
