### ISSUE TITLE
#5 User Story Create Content resources.js

### ISSUE THREAD

**Issue by dorosiemers** [dorosiemers/capstone-test#5]
# Value Proposition
As a User I want to access information and links about Hilfestellen and Fachberatungen.

# Description
There's information and links available as a list on the content page. 

![User Stories Skribble 5](https://user-images.githubusercontent.com/112318280/197553337-f2f98ac7-b914-4f73-a0a4-4b45878460b3.png)

# Acceptance Criteria
- [ ] each list item is accompanied by a link or contact information

# Tasks
 - [ ] generate a list of Hilfestellen and Fachberatungen
 - [ ] add links and contact info
