### ISSUE TITLE
#6 Input to List Entry

### ISSUE THREAD

**Issue by dorosiemers** [dorosiemers/capstone-test#6]
# Value Proposition
As a User I want to enter my data and save it as a list item on the list page.

# Description
The input form is working and the data is saved as a list item.

![User Stories Skribble 6](https://user-images.githubusercontent.com/112318280/199251790-d2c7f94c-c5dd-4ef9-8f1d-c3b8ad14c79b.png)

# Acceptance Criteria
- [ ] I can input data that will then show up as a list entry on my list page.

# Tasks
 - [ ] add a submit button 
 - [ ] render and save the data in the list component
